# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-24 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Align',
            fields=[
                ('id_alg', models.AutoField(primary_key=True, serialize=False)),
                ('id_ctt', models.IntegerField()),
                ('id_ctt_search_db', models.IntegerField()),
                ('al_score', models.FloatField()),
                ('al_type', models.CharField(max_length=7)),
                ('chain', models.CharField(max_length=1)),
                ('pdbid', models.CharField(max_length=5)),
                ('r1', models.CharField(max_length=7)),
                ('r2', models.CharField(max_length=7)),
                ('rotation', models.TextField()),
                ('translation', models.TextField()),
                ('clash', models.IntegerField()),
                ('ddg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'align',
            },
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id_atom', models.AutoField(primary_key=True, serialize=False)),
                ('id_ctt', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('name', models.CharField(max_length=5)),
                ('level', models.CharField(max_length=5)),
                ('bfactor', models.FloatField()),
                ('occupancy', models.FloatField()),
                ('element', models.CharField(max_length=10)),
                ('serial_number', models.IntegerField()),
                ('fullname', models.CharField(max_length=10)),
                ('coord', models.CharField(max_length=30)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'atom',
            },
        ),
        migrations.CreateModel(
            name='AtomAlign',
            fields=[
                ('id_atom', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('level', models.CharField(max_length=5)),
                ('bfactor', models.FloatField()),
                ('occupancy', models.FloatField()),
                ('element', models.CharField(max_length=10)),
                ('serial_number', models.IntegerField()),
                ('fullname', models.CharField(max_length=10)),
                ('coord', models.CharField(max_length=25)),
                ('id_align', models.IntegerField()),
            ],
            options={
                'db_table': 'atom_align',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id_ctt', models.AutoField(primary_key=True, serialize=False)),
                ('id_p', models.IntegerField()),
                ('ctt_type', models.CharField(max_length=30)),
                ('ctt_status', models.IntegerField()),
                ('ctt_chain', models.CharField(max_length=4)),
                ('ctt_sequence', models.IntegerField()),
                ('ctt_clash', models.IntegerField()),
                ('ctt_ddg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id_p', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('status', models.IntegerField()),
                ('pdbid', models.CharField(max_length=45)),
                ('cutoff', models.FloatField()),
                ('url', models.CharField(max_length=64)),
                ('notification_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processing',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_u', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
