# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proteus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='align',
            name='ddg',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='align',
            name='id_ctt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteus.Contact'),
        ),
        migrations.AlterField(
            model_name='atom',
            name='id_ctt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteus.Contact'),
        ),
        migrations.AlterField(
            model_name='atomalign',
            name='id_align',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='align', to='proteus.Align'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ctt_ddg',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='proteus.Processing'),
        ),
        migrations.AlterField(
            model_name='processing',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='proteus.User'),
        ),
    ]
